//! Regular convex 4-polytopes
//!
//! All 6 regular convex 4-polytopes, centered at the origin.
//! Vertex and edge data generated by `tools/generate_polytopes.py`.
//!
//! | Name | Vertices | Edges | Cells |
//! |------|----------|-------|-------|
//! | 5-cell (pentachoron) | 5 | 10 | 5 |
//! | 8-cell (tesseract) | 16 | 32 | 8 |
//! | 16-cell | 8 | 24 | 16 |
//! | 24-cell | 24 | 96 | 24 |
//! | 600-cell | 120 | 720 | 600 |
//! | 120-cell | 600 | 1200 | 120 |

use bytemuck::{Pod, Zeroable};

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Pod, Zeroable)]
pub struct Vertex4D {
    pub position: [f32; 4],
}

impl Vertex4D {
    pub fn new(x: f32, y: f32, z: f32, w: f32) -> Self {
        Self {
            position: [x, y, z, w],
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum PolytopeType {
    FiveCell,
    #[default]
    EightCell,
    SixteenCell,
    TwentyFourCell,
    SixHundredCell,
    HundredTwentyCell,
}

impl PolytopeType {
    pub fn name(&self) -> &'static str {
        match self {
            PolytopeType::FiveCell => "5-cell (Pentachoron)",
            PolytopeType::EightCell => "8-cell (Tesseract)",
            PolytopeType::SixteenCell => "16-cell",
            PolytopeType::TwentyFourCell => "24-cell",
            PolytopeType::SixHundredCell => "600-cell",
            PolytopeType::HundredTwentyCell => "120-cell",
        }
    }

    pub fn short_name(&self) -> &'static str {
        match self {
            PolytopeType::FiveCell => "5-cell",
            PolytopeType::EightCell => "tesseract",
            PolytopeType::SixteenCell => "16-cell",
            PolytopeType::TwentyFourCell => "24-cell",
            PolytopeType::SixHundredCell => "600-cell",
            PolytopeType::HundredTwentyCell => "120-cell",
        }
    }

    pub fn vertex_count(&self) -> usize {
        match self {
            PolytopeType::FiveCell => 5,
            PolytopeType::EightCell => 16,
            PolytopeType::SixteenCell => 8,
            PolytopeType::TwentyFourCell => 24,
            PolytopeType::SixHundredCell => 120,
            PolytopeType::HundredTwentyCell => 600,
        }
    }

    pub fn edge_count(&self) -> usize {
        match self {
            PolytopeType::FiveCell => 10,
            PolytopeType::EightCell => 32,
            PolytopeType::SixteenCell => 24,
            PolytopeType::TwentyFourCell => 96,
            PolytopeType::SixHundredCell => 720,
            PolytopeType::HundredTwentyCell => 1200,
        }
    }

    pub fn all() -> [PolytopeType; 6] {
        [
            PolytopeType::FiveCell,
            PolytopeType::EightCell,
            PolytopeType::SixteenCell,
            PolytopeType::TwentyFourCell,
            PolytopeType::SixHundredCell,
            PolytopeType::HundredTwentyCell,
        ]
    }
}

pub fn create_polytope(kind: PolytopeType) -> (Vec<Vertex4D>, Vec<u16>) {
    match kind {
        PolytopeType::FiveCell => create_5_cell(),
        PolytopeType::EightCell => create_8_cell(),
        PolytopeType::SixteenCell => create_16_cell(),
        PolytopeType::TwentyFourCell => create_24_cell(),
        PolytopeType::SixHundredCell => create_600_cell(),
        PolytopeType::HundredTwentyCell => create_120_cell(),
    }
}

include!("polytopes_data.rs");

#[cfg(test)]
mod tests {
    use super::*;

    const EPSILON: f32 = 1e-5;

    fn distance_sq(v1: &Vertex4D, v2: &Vertex4D) -> f32 {
        (0..4)
            .map(|i| (v1.position[i] - v2.position[i]).powi(2))
            .sum()
    }

    fn centroid(vertices: &[Vertex4D]) -> [f32; 4] {
        let n = vertices.len() as f32;
        let mut c = [0.0f32; 4];
        for v in vertices {
            for (i, acc) in c.iter_mut().enumerate() {
                *acc += v.position[i];
            }
        }
        for acc in &mut c {
            *acc /= n;
        }
        c
    }

    fn count_antipodal_pairs(vertices: &[Vertex4D]) -> usize {
        let mut count = 0;
        for i in 0..vertices.len() {
            for j in (i + 1)..vertices.len() {
                let v1 = &vertices[i];
                let v2 = &vertices[j];
                let is_antipodal =
                    (0..4).all(|k| (v1.position[k] + v2.position[k]).abs() < EPSILON);
                if is_antipodal {
                    count += 1;
                }
            }
        }
        count
    }

    fn uniform_edge_lengths(vertices: &[Vertex4D], indices: &[u16]) -> bool {
        if indices.len() < 2 {
            return true;
        }
        let first_dist_sq = distance_sq(
            &vertices[indices[0] as usize],
            &vertices[indices[1] as usize],
        );
        indices.chunks(2).all(|chunk| {
            let d = distance_sq(&vertices[chunk[0] as usize], &vertices[chunk[1] as usize]);
            (d - first_dist_sq).abs() < 1e-3 * first_dist_sq.max(1.0)
        })
    }

    fn compute_vertex_degrees(vertices: &[Vertex4D], indices: &[u16]) -> Vec<usize> {
        let mut degrees = vec![0usize; vertices.len()];
        for chunk in indices.chunks(2) {
            degrees[chunk[0] as usize] += 1;
            degrees[chunk[1] as usize] += 1;
        }
        degrees
    }

    macro_rules! polytope_tests {
        ($name:ident, $create_fn:ident, $v:expr, $e:expr, $deg:expr, $anti:expr) => {
            #[test]
            fn $name() {
                let (vertices, indices) = $create_fn();
                assert_eq!(vertices.len(), $v, "vertex count");
                assert_eq!(indices.len() / 2, $e, "edge count");

                let c = centroid(&vertices);
                for i in 0..4 {
                    assert!(c[i].abs() < EPSILON, "centroid not at origin: {:?}", c);
                }

                assert!(
                    uniform_edge_lengths(&vertices, &indices),
                    "edges not uniform"
                );

                let degrees = compute_vertex_degrees(&vertices, &indices);
                for (i, &d) in degrees.iter().enumerate() {
                    assert_eq!(
                        d, $deg,
                        "vertex {} should have degree {}, got {}",
                        i, $deg, d
                    );
                }

                assert_eq!(count_antipodal_pairs(&vertices), $anti, "antipodal pairs");
            }
        };
    }

    polytope_tests!(test_5_cell, create_5_cell, 5, 10, 4, 0);
    polytope_tests!(test_8_cell, create_8_cell, 16, 32, 4, 8);
    polytope_tests!(test_16_cell, create_16_cell, 8, 24, 6, 4);
    polytope_tests!(test_24_cell, create_24_cell, 24, 96, 8, 12);
    polytope_tests!(test_600_cell, create_600_cell, 120, 720, 12, 60);
    polytope_tests!(test_120_cell, create_120_cell, 600, 1200, 4, 300);

    #[test]
    fn test_polytope_type_metadata() {
        assert_eq!(PolytopeType::FiveCell.vertex_count(), 5);
        assert_eq!(PolytopeType::FiveCell.edge_count(), 10);

        assert_eq!(PolytopeType::EightCell.vertex_count(), 16);
        assert_eq!(PolytopeType::EightCell.edge_count(), 32);

        assert_eq!(PolytopeType::SixteenCell.vertex_count(), 8);
        assert_eq!(PolytopeType::SixteenCell.edge_count(), 24);

        assert_eq!(PolytopeType::TwentyFourCell.vertex_count(), 24);
        assert_eq!(PolytopeType::TwentyFourCell.edge_count(), 96);

        assert_eq!(PolytopeType::SixHundredCell.vertex_count(), 120);
        assert_eq!(PolytopeType::SixHundredCell.edge_count(), 720);

        assert_eq!(PolytopeType::HundredTwentyCell.vertex_count(), 600);
        assert_eq!(PolytopeType::HundredTwentyCell.edge_count(), 1200);
    }
}
